-- INSERT INTO CUSTOMER_LIST VALUES(1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'admin@gmail.com', 'admin', '관리자', 'test');
-- INSERT INTO CUSTOMER_LIST VALUES(2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,'javajigi@gmail.com', 'test', '일반', 'test');


-- INSERT INTO CUSTOMER_LIST VALUES(1, 'admin', 'test', '관리자', 'javajigi@gmail.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
-- INSERT INTO CUSTOMER_LIST VALUES(2, 'test', 'test', '일반', 'test@gmail.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);