CREATE TABLE CUSTOMER_LIST(
ID LONG NOT NULL AUTO_INCREMENT,
USER_ID VARCHAR(20) NOT NULL,
USER_PW VARCHAR(255) NOT NULL,
USER_NAME VARCHAR(15) NOT NULL,
USER_EMAIL VARCHAR(30) NOT NULL,
PRIMARY KEY(ID));